### ISSUE TITLE
mark watched videos as marked/icon?

### ISSUE THREAD

**Issue by nwgat** [bmlzootown/Hydravion-AndroidTV#11]
would been neat if the video i just watched was marked "watched" or a icon

**Comment by NickM-27** [comment]
@nwgat What about a bar across the video images that show progress in video (like YouTube does)

![image](https://user-images.githubusercontent.com/14866235/154175254-dea4b63d-e668-4a92-872b-66ec969f21df.png)

**Comment by nwgat** [comment]
that works too

**Comment by bmlzootown** [comment]
Implemented per https://github.com/bmlzootown/Hydravion-AndroidTV/pull/14.
