### ISSUE TITLE
Can’t Login! Session Expired Error!

### ISSUE THREAD

**Issue by canyon1991** [bmlzootown/Hydravion-AndroidTV#18]
Nvidia Shield Pro running version 9.1.0 (33.2.0.125)

Hydravion version 1.4.4

When I log in, it says “Session Expired. Re-open Hydravion to login again!”. 

![image](https://user-images.githubusercontent.com/56959429/179578873-4e6eff52-573c-4b46-b028-aede3354211d.jpg)

**Comment by bmlzootown** [comment]
Howdy!

Are you, by chance, able to connect via ADB and grab logs while recreating the issue?

**Comment by bmlzootown** [comment]
If you haven't already, try the newest release: https://github.com/bmlzootown/Hydravion-AndroidTV/releases/tag/v1.4.5

**Comment by canyon1991** [comment]
I tried it with the latest version and it worked. 
When I tried to login the first time didn't do anything, so I tried again and the app crashed/closed. I opened the app and it was legged in. 
Thank you for the hard work and support to the community.
