### ISSUE TITLE
"Video could not be played" all resolutions

### ISSUE THREAD

**Issue by pannal** [bmlzootown/Hydravion-AndroidTV#21]
Hey,

I can play videos in the official floatplane app without issues, but lately I get "Video could not be played" for every video and resolution on the LTT supporter plus channel using hydration 1.4.5.

Edit: signing out and in again doesn't help either

**Comment by bmlzootown** [comment]
They've changed up some API responses, it seems. Working on a fix for both AndroidTV and Roku.

**Comment by delano8** [comment]
Problem is back here.
