### ISSUE TITLE
"Video could not be played" on all videos

### ISSUE THREAD

**Issue by delano8** [bmlzootown/Hydravion-AndroidTV#27]
Both on the AndroidTV play store version, and the apk version (1.4.8) have stopped working for me. Every video shows the same error, "Video could not be played". I know, it's probably the fault of floatplane because you don't work with you when they change the site. Just thought I'd let you know, in case you didn't know yet.

Thanks for creating this awesome app. Love to use it!

**Comment by delano8** [comment]
Wow you're totally right when I click a resolution below 4k manually it does work. Should have tried that.

**Comment by bmlzootown** [comment]
It looks like they've switched to providing all possible resolutions for a video regardless as to whether a user has access and have instead added an ```enabled``` field for each variant. I've fixed the issue locally, but I'm holding off on pushing a release until I can fix an issue related to new videos being posted (https://github.com/bmlzootown/Hydravion-AndroidTV/issues/26). Assuming a video drops today, I should be able to get a build up here and a release scheduled for the Play store.

I'll post an update when the release is up.

**Comment by bmlzootown** [comment]
> Also now that you're here anyway, just wondering, is there a difference between the apk version here, and the play store version?

The store variant is version 1.5.0, whereas it seems the latest version uploaded here is 1.4.8. Seems I never pushed the last update here. 🤦

**Comment by delano8** [comment]
That's funny. So usually they are the same then? Sometimes off-store app have more features because the store doesn't allow them or something.

**Comment by bmlzootown** [comment]
If you would, try the latest beta under releases and let me know if the issue(s) persist.

**Comment by bmlzootown** [comment]
> Yep, it all works again with this version.
> 
> However on startup it says I should update to 1.4.8 lol.

Yeah, that's due to the fact that I set it as a pre-release. It won't prompt anymore once the actual update is pushed.

**Comment by delano8** [comment]
New issue in this beta (picture is of my tv).

https://i.imgur.com/AZyumoq.jpg

I watched 3 videos from start to finish, nu issue. Then I watched this video, it stopped playing at around 80%, then this happened. I couldn't get back to the overview or resume the video, I had to go out of the app completely and restart it to watch anything again.

**Comment by marklahn** [comment]
> New issue in this beta (picture is of my tv).
> 
> https://i.imgur.com/AZyumoq.jpg
> 
> I watched 3 videos from start to finish, no issue. Then I watched this video, it stopped playing at around 80%, then this happened. I couldn't get back to the overview or resume the video, I had to go out of the app completely and restart it to watch anything again.

Please create a new issue for a new bug then, it doesn't belong in this thread :)

**Comment by delano8** [comment]
Closed issue as this resolution problem was solved. Opened #28 for new issues.
