### ISSUE TITLE
Update Available Bug on 1.5.1

### ISSUE THREAD

**Issue by nwgat** [bmlzootown/Hydravion-AndroidTV#29]
Everytime i open Hydravion i get "Update Available" message, is there a way to disable new update notication?

**Comment by delano8** [comment]
Dev can fix it by releasing a non-beta but I'm guessing he gave up on us :(

**Comment by bmlzootown** [comment]
Sorry, I've been extra busy at work and at home as of late -- if I'm able, I'll push an update this afternoon to fix the update message.

**Comment by delano8** [comment]
No worries if you're busy you're busy, I was just wondering if you've given
up. There's also other issues like crashing, the double info panel etc, but
you'll look at those at some point in the future?
Thanks
Kind regards
Delano Böhm

**Comment by bmlzootown** [comment]
See #28 for current status.

The new pre-release should fix the update notification issue -- I'll leave this issue open until such is confirmed.

**Comment by nwgat** [comment]
new update fixes "new update notification" issue, keep up the good work

**Comment by delano8** [comment]
The update popup has indeed been solved now!
