### ISSUE TITLE
Parsing error on Fire TV

### ISSUE THREAD

**Issue by mapelpapel** [bmlzootown/Hydravion-AndroidTV#4]
When I try to install the app on a fire tv stick, I get a parsing error. 
Fire TV 4k
Fire OS 6.2.8.0

**Comment by NickM-27** [comment]
@mapelpapel Fire OS 6.x is built upon Android 7 which is not supported by this app. A device which supports Fire OS 7 (maybe check for updates?) would allow the app to be installed.
