### ISSUE TITLE
Crashing Post-Login

### ISSUE THREAD

**Issue by bmlzootown** [bmlzootown/Hydravion-AndroidTV#9]
Two users, one via LTT forums and the other via Discord, have reported that, after authenticating, the app simply crashes upon launch.

Delicioussandwiches
- v1.3.2
- Bravia X90J Smart Google TV

Sivilian
- presumably v1.3.2
- 2017 Nvidia Shield

Other users can run the app just fine, tested on both another Nvidia Shield and the latest Chromecast with no issues. Might be a subscription (tier) specific issue.

Still waiting to hear back from both users in order to get a logcat dump so that I can look into the issue.

**Comment by francobarber** [comment]
I just tried to install and use version 1.3.3 on an Nvidia shield tv, and have the same post login crash.
How can I collect the log dump you need?

**Comment by bmlzootown** [comment]
You'd need to connect to the device via ADB and capture the logcat output. The former will have to be installed, but I posted a short explanation of how to capture said output on the LTT forum: https://linustechtips.com/topic/1052617-floatplane-unofficial-rokutvosandroidtv-channel/?do=findComment&comment=14865590

If you need more help, just let me know! Thanks!

**Comment by francobarber** [comment]
I got the logcat output.

[logcat-fail.txt](https://github.com/bmlzootown/Hydravion-AndroidTV/files/7457654/logcat-fail.txt)

**Comment by bmlzootown** [comment]
> I got the logcat output.
> 
> [logcat-fail.txt](https://github.com/bmlzootown/Hydravion-AndroidTV/files/7457654/logcat-fail.txt)

Figured it out. The issue was Level1Techs. The base subscription tier (rather than the yearly tier) doesn't provide livestream access, leading to the following error:
`
11-01 21:07:38.012  3875  3971 E Volley  : [7276] NetworkUtility.shouldRetryException: Unexpected response code 403 for https://www.floatplane.com/api/cdn/delivery?type=live&creator=5d48c7be5fa46b731f1d5885
11-01 21:07:38.012  3875  3875 W System.err: com.android.volley.AuthFailureError
11-01 21:07:38.012  3875  3875 W System.err: 	at com.android.volley.toolbox.NetworkUtility.shouldRetryException(NetworkUtility.java:189)
11-01 21:07:38.012  3875  3875 W System.err: 	at com.android.volley.toolbox.BasicNetwork.performRequest(BasicNetwork.java:145)
11-01 21:07:38.012  3875  3875 W System.err: 	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:132)
11-01 21:07:38.012  3875  3875 W System.err: 	at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
11-01 21:07:38.012  3875  3875 W System.err: 	at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)
11-01 21:07:38.993  3875  3875 D AndroidRuntime: Shutting down VM
--------- beginning of crash
11-01 21:07:38.994  3875  3875 E AndroidRuntime: FATAL EXCEPTION: main
11-01 21:07:38.994  3875  3875 E AndroidRuntime: Process: ml.bmlzootown.hydravion, PID: 3875
11-01 21:07:38.994  3875  3875 E AndroidRuntime: java.lang.NullPointerException
11-01 21:07:38.994  3875  3875 E AndroidRuntime: 	at java.util.Objects.requireNonNull(Objects.java:203)
11-01 21:07:38.994  3875  3875 E AndroidRuntime: 	at ml.bmlzootown.hydravion.browse.MainFragment.refreshRows(MainFragment.java:372)
11-01 21:07:38.994  3875  3875 E AndroidRuntime: 	at ml.bmlzootown.hydravion.browse.MainFragment.gotVideos(MainFragment.java:344)
11-01 21:07:38.994  3875  3875 E AndroidRuntime: 	at ml.bmlzootown.hydravion.browse.MainFragment.lambda$gotSubscriptions$8$MainFragment(MainFragment.java:314)
11-01 21:07:38.994  3875  3875 E AndroidRuntime: 	at ml.bmlzootown.hydravion.browse.-$$Lambda$MainFragment$FMQbAe1jxGn_fpaYncqiGGOC9WM.invoke(Unknown Source:6)
11-01 21:07:38.994  3875  3875 E AndroidRuntime: 	at ml.bmlzootown.hydravion.client.HydravionClient$getVideos$1.onSuccessCreator(HydravionClient.kt:99)
11-01 21:07:38.994  3875  3875 E AndroidRuntime: 	at ml.bmlzootown.hydravion.client.RequestTask$sendRequest$stringRequest$5.onResponse(RequestTask.kt:80)
11-01 21:07:38.994  3875  3875 E AndroidRuntime: 	at ml.bmlzootown.hydravion.client.RequestTask$sendRequest$stringRequest$5.onResponse(RequestTask.kt:76)
11-01 21:07:38.994  3875  3875 E AndroidRuntime: 	at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:82)
11-01 21:07:38.994  3875  3875 E AndroidRuntime: 	at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:29)
11-01 21:07:38.994  3875  3875 E AndroidRuntime: 	at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
11-01 21:07:38.994  3875  3875 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
11-01 21:07:38.994  3875  3875 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-01 21:07:38.994  3875  3875 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
11-01 21:07:38.994  3875  3875 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6721)
11-01 21:07:38.994  3875  3875 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-01 21:07:38.994  3875  3875 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
11-01 21:07:38.994  3875  3875 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
11-01 21:07:38.996  3665  4059 W ActivityManager:   Force finishing activity ml.bmlzootown.hydravion/.browse.MainActivity
`

I've done a quick fix for this and will push the update to the repo, then upload an updated APK. Thanks for helping finally close this issue!
